name: flutter_modal_dialog
description: "A package for flutter to show modal dialogs."
version: 0.0.1
homepage: https://github.com/nickolasdeluca/modal_dialog

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
